# Generated by Django 4.2.5 on 2023-10-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
