# Generated by Django 4.2.5 on 2023-10-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PLONGEUR', 'Plongeur'), ('FORMATEUR', 'Formateur')], default='PLONGEUR', max_length=10),
        ),
    ]
