# Generated by Django 4.2.5 on 2023-11-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_users', '0005_alter_diverprofile_emergency_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PLONGEUR', 'Plongeur'), ('FORMATEUR', 'Formateur'), ('ADMIN', 'Admin')], default='PLONGEUR', max_length=10),
        ),
    ]
