# Generated by Django 4.2.5 on 2023-11-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_users', '0009_remove_divegroup_leader_remove_divegroup_members_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiveGroup',
        ),
    ]
