# Generated by Django 4.2.5 on 2023-11-15 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_users', '0010_delete_divegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiveGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField(unique=True, verbose_name='Group Number')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('boat_driver', models.ForeignKey(limit_choices_to={'role': 'FORMATEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_dive_groups_as_driver', to=settings.AUTH_USER_MODEL, verbose_name='Boat Driver')),
                ('divers', models.ManyToManyField(limit_choices_to={'role': 'PLONGEUR'}, related_name='dive_groups', to=settings.AUTH_USER_MODEL, verbose_name='Divers')),
                ('trainer_one', models.ForeignKey(limit_choices_to={'role': 'FORMATEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_dive_groups_as_trainer_one', to=settings.AUTH_USER_MODEL, verbose_name='First Trainer')),
                ('trainer_two', models.ForeignKey(limit_choices_to={'role': 'FORMATEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_dive_groups_as_trainer_two', to=settings.AUTH_USER_MODEL, verbose_name='Second Trainer')),
            ],
        ),
    ]
