# Generated by Django 4.2.5 on 2023-12-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_users', '0011_divegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diverprofile',
            name='cumulative_dives_in_logbook',
        ),
        migrations.RemoveField(
            model_name='diverprofile',
            name='logbook_number',
        ),
        migrations.RemoveField(
            model_name='diverprofile',
            name='total_dives',
        ),
    ]
