# Generated by Django 4.2.5 on 2023-12-07 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_users', '0012_remove_diverprofile_cumulative_dives_in_logbook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diverprofile',
            name='emergency_contact',
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='diver_profile',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='MQ_users.diverprofile'),
            preserve_default='True',
        ),
    ]
