# Generated by Django 4.2.5 on 2023-12-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_users', '0013_remove_diverprofile_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('DIVER', 'Diver'), ('INSTRUCTOR', 'Instructor'), ('ADMIN', 'Admin')], default='DIVER', max_length=10),
        ),
    ]
