# Generated by Django 4.2.5 on 2023-12-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_users', '0014_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diverprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='diverprofile',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='diverprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='diverprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='diverprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
