# Generated by Django 4.2.5 on 2023-12-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_users', '0015_alter_diverprofile_city_alter_diverprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diverprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diverprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
