# Generated by Django 4.2.5 on 2023-12-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_users', '0016_alter_diverprofile_address_alter_diverprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': "Un utilisateur avec ce nom d'utilisateur existe déjà."}, help_text='Requis. 150 caractères ou moins.', max_length=150, unique=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='diver_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='MQ_users.diverprofile'),
        ),
    ]
