# Generated by Django 4.2.5 on 2023-12-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_users', '0017_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diverprofile',
            name='role',
        ),
    ]
