# Generated by Django 4.2.5 on 2023-12-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_users', '0018_remove_diverprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='diver_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='MQ_users.diverprofile'),
        ),
    ]
