# Generated by Django 4.2.5 on 2024-01-15 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_users', '0021_alter_divegroup_boat_driver_alter_divegroup_divers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divegroup',
            name='group_number',
        ),
        migrations.AddField(
            model_name='divegroup',
            name='group_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Group Description'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='diver_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='MQ_users.diverprofile'),
        ),
    ]
