# Generated by Django 4.2.5 on 2024-01-23 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_users', '0024_alter_divegroup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
