# Generated by Django 4.2.5 on 2023-11-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_diving_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divinglog',
            name='wind',
            field=models.CharField(blank=True, choices=[('nul', 'Nul'), ('faible', 'Faible'), ('fort', 'Fort')], max_length=10, verbose_name='Wind'),
        ),
        migrations.AlterField(
            model_name='divinglog',
            name='current',
            field=models.CharField(blank=True, choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('fort', 'Fort')], max_length=10, verbose_name='Current'),
        ),
        migrations.AlterField(
            model_name='divinglog',
            name='visibility',
            field=models.CharField(blank=True, choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('bonne', 'Bonne')], max_length=10, verbose_name='Visibility'),
        ),
        migrations.AlterField(
            model_name='divinglog',
            name='weather',
            field=models.CharField(blank=True, choices=[('soleil', 'Soleil'), ('nuage', 'Nuage'), ('pluie', 'Pluie')], max_length=10, verbose_name='Weather'),
        ),
    ]
