# Generated by Django 4.2.5 on 2023-11-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_diving_logs', '0002_divinglog_wind_alter_divinglog_current_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divinglog',
            name='wind',
        ),
        migrations.AlterField(
            model_name='divinglog',
            name='weather',
            field=models.CharField(blank=True, choices=[('soleil', 'Soleil'), ('nuage', 'Nuage'), ('pluie', 'Pluie'), ('averse', 'Averse')], max_length=10, verbose_name='Weather'),
        ),
    ]
