# Generated by Django 4.2.5 on 2023-11-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_diving_logs', '0003_remove_divinglog_wind_alter_divinglog_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divinglog',
            name='bottle_type',
            field=models.CharField(blank=True, choices=[('6l', '6 Liters'), ('12l', '12 Liters'), ('15l', '15 Liters')], max_length=3, verbose_name='Bottle Type'),
        ),
        migrations.AlterField(
            model_name='divinglog',
            name='wet_suit',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2, verbose_name='Wet Suit'),
        ),
    ]
