# Generated by Django 4.2.5 on 2023-11-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_diving_logs', '0004_alter_divinglog_bottle_type_alter_divinglog_wet_suit'),
    ]

    operations = [
        migrations.AddField(
            model_name='divinglog',
            name='wind',
            field=models.CharField(blank=True, choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('fort', 'Fort')], max_length=10, verbose_name='Wind'),
        ),
    ]
