# Generated by Django 4.2.5 on 2023-11-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_diving_logs', '0005_divinglog_wind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorcomment',
            name='comment',
            field=models.TextField(verbose_name='Comment'),
        ),
    ]
