# Generated by Django 4.2.5 on 2023-12-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_diving_logs', '0006_alter_instructorcomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divinglog',
            name='current',
            field=models.CharField(blank=True, choices=[('weak', 'Weak'), ('medium', 'Medium'), ('strong', 'Strong')], max_length=10, verbose_name='Current'),
        ),
        migrations.AlterField(
            model_name='divinglog',
            name='status',
            field=models.CharField(choices=[('AWAITING', 'Awaiting'), ('VALIDATED', 'Validated'), ('REFUSED', 'Refused')], default='AWAITING', max_length=10),
        ),
        migrations.AlterField(
            model_name='divinglog',
            name='visibility',
            field=models.CharField(blank=True, choices=[('bad', 'Bad'), ('medium', 'Medium'), ('good', 'Good')], max_length=10, verbose_name='Visibility'),
        ),
        migrations.AlterField(
            model_name='divinglog',
            name='weather',
            field=models.CharField(blank=True, choices=[('sun', 'Sun'), ('cloud', 'Cloud'), ('rain', 'Rain'), ('downpour', 'Downpour')], max_length=10, verbose_name='Weather'),
        ),
        migrations.AlterField(
            model_name='divinglog',
            name='wind',
            field=models.CharField(blank=True, choices=[('weak', 'Weak'), ('medium', 'Medium'), ('strong', 'Strong')], max_length=10, verbose_name='Wind'),
        ),
    ]
