# Generated by Django 4.2.5 on 2023-12-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_users', '0020_alter_emergencycontact_diver_profile'),
        ('MQ_diving_logs', '0008_alter_divinglog_current_alter_divinglog_wind'),
    ]

    operations = [
        migrations.AddField(
            model_name='divinglog',
            name='dive_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MQ_users.divegroup', verbose_name='Dive Group'),
        ),
    ]
