# Generated by Django 4.2.5 on 2024-01-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_users', '0024_alter_divegroup_date'),
        ('MQ_diving_logs', '0010_remove_divinglog_signature_remove_divinglog_stamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorcomment',
            name='dive_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_comments', to='MQ_users.divegroup'),
            preserve_default=False,
        ),
    ]
