# Generated by Django 4.2.5 on 2024-01-16 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_diving_logs', '0011_instructorcomment_dive_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorcomment',
            name='dive_group',
        ),
    ]
