# Generated by Django 4.2.5 on 2024-01-16 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_users', '0024_alter_divegroup_date'),
        ('MQ_diving_logs', '0012_remove_instructorcomment_dive_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorcomment',
            name='dive_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_comments', to='MQ_users.divegroup'),
        ),
        migrations.AlterField(
            model_name='instructorcomment',
            name='diving_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MQ_diving_logs.divinglog'),
        ),
    ]
