# Generated by Django 4.2.5 on 2024-02-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQ_diving_logs', '0013_instructorcomment_dive_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divinglog',
            name='status',
            field=models.CharField(choices=[('AWAITING', 'Awaiting'), ('VALIDATED', 'Validated'), ('REFUSED', 'Refused')], default='AWAITING', max_length=10),
        ),
    ]
